#!/usr/bin/env bash
#> tlaplus <command>
#>
#> COMMANDS:
#>     tlc [args] <file>
#>     pcal [args] <module>
#>     sany <file>
#>     repl
#>     tex <file>
#>     pdf <file>
#>     pm <file>

METADIR=./metadir

do_help() {
  sed -n -E '/^#>/s/^#>[ ]?//p' < "$0"
  exit 1
}

run() {
  docker run \
    --rm \
    -it \
    -w /workdir \
    -v "$(pwd)":/workdir \
    creasty/tlaplus:latest \
    "$@"
}

run_tool() {
  run java -XX:+UseParallelGC -classpath /usr/lib/tla2tools.jar "$@"
}

ensure_metadir() {
  [ -d "$METADIR" ] || mkdir -p "$METADIR"
}

#  Entrypoint
#-----------------------------------------------
TOOL_NAME="${1:-}"
shift || true

case "$TOOL_NAME" in
  tlc)
    run_tool tlc2.TLC "$@"
    ;;
  pcal)
    run_tool pcal.trans "$@"
    ;;
  sany)
    run_tool tla2sany.SANY "$@"
    ;;
  repl)
    run_tool tlc2.REPL "$@"
    ;;
  tex)
    ensure_metadir
    run_tool tla2tex.TLA -shade -metadir "$METADIR" "$@"
    ;;
  pdf)
    ensure_metadir
    run_tool tla2tex.TLA -shade -latexCommand pdflatex -latexOutputExt pdf -metadir "$METADIR" "$@"
    ;;
  pm)
    # Not supported yet
    run /usr/bin/tlapm -I /usr/lib/tlaps "$@"
    ;;
  sh)
    # For debugging
    run sh
    ;;
  *)
    do_help
    ;;
esac
